# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NR_oriYmI2jdOHLVGAgGj0E9EoaiFfQI
"""

# main.py
from fastapi import FastAPI
from router_food import router as food_router

app = FastAPI()
app.include_router(food_router)