# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OiymQwXtAbiiOvuoYzPWRJEvNb4sKvYb
"""
from pillow_heif import register_heif_opener
register_heif_opener()

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from router_food import router as food_router

app = FastAPI()

# ──────────────── CORS 설정 ──────────────── #
origins = [
    "http://localhost:3000",      # 로컬 프론트엔드
    "http://127.0.0.1:3000",
    "http://192.168.0.6:3000",
    "http://192.168.0.6:8080",
    "http://0.0.0.0:8080",
    "http://0.0.0.0:3000",
    "http://168.131.30.87:8080",
    "http://168.131.30.87:3000",
    "https://your-frontend.com",  # 배포용 프론트엔드 주소
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,       # 허용할 origin 목록
    allow_credentials=True,
    allow_methods=["*"],         # 모든 HTTP 메서드 허용
    allow_headers=["*"],         # 모든 헤더 허용
)

# ──────────────── 라우터 등록 ──────────────── #
app.include_router(food_router)